AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Test Serverless API

Resources:
  <STACK>: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./swagger.yaml
