AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless API Gateway

Resources:
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./swagger.yaml
