AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless API Gateway
Globals:
  Api:
    OpenApiVersion: 3.0.1
Resources:
  ApiGatewayServer<NODE_ENV>:
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./server.yaml
      
  ApiGatewayAdmin<NODE_ENV>:
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./admin.yaml
      
  ApiGatewayHotel<NODE_ENV>:
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./hotel.yaml
Outputs:
  ApiGatewayServer<NODE_ENV>:
    Description: 'API Gateway For Server endpoint URL'
    Value: !Sub 'https://${ApiGatewayServer<NODE_ENV>}.execute-api.${AWS::Region}.amazonaws.com/<NODE_ENV>/'
  ApiGatewayServer<NODE_ENV>RestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref ApiGatewayServer<NODE_ENV>
    Export:
      Name:  ApiGatewayServer<NODE_ENV>-RestApiId
  ApiGateway<NODE_ENV>RootResourceId:
    Value: !GetAtt  ApiGatewayServer<NODE_ENV>.RootResourceId
    Export:
      Name:  ApiGatewayServer<NODE_ENV>-RootResourceId
      
  ApiGatewayAdmin<NODE_ENV>:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ApiGatewayAdmin<NODE_ENV>}.execute-api.${AWS::Region}.amazonaws.com/<NODE_ENV>/'
  ApiGatewayAdmin<NODE_ENV>RestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref ApiGatewayAdmin<NODE_ENV>
    Export:
      Name:  ApiGatewayAdmin<NODE_ENV>-RestApiId
  ApiGatewayAdmin<NODE_ENV>RootResourceId:
    Value: !GetAtt  ApiGatewayAdmin<NODE_ENV>.RootResourceId
    Export:
      Name:  ApiGatewayAdmin<NODE_ENV>-RootResourceId
