AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless API Gateway
Globals:
  Api:
    OpenApiVersion: 3.0.1
Resources:
  ApiGateway<NODE_ENV>:
    Type: AWS::Serverless::Api
    Properties:
      StageName: <NODE_ENV>
      DefinitionUri: ./swagger.yaml
Outputs:
  ApiGateway<NODE_ENV>:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ApiGateway<NODE_ENV>}.execute-api.${AWS::Region}.amazonaws.com/<NODE_ENV>/'
  ApiGateway<NODE_ENV>RestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref ApiGateway<NODE_ENV>
    Export:
      Name:  ApiGateway<NODE_ENV>-RestApiId
  ApiGateway<NODE_ENV>RootResourceId:
    Value: !GetAtt  ApiGateway<NODE_ENV>.RootResourceId
    Export:
      Name:  ApiGateway<NODE_ENV>-RootResourceId
